SERPAPI_KEY = "a5e67e2ac811a86ebd77129fbe22a49280935b728f4ef37a58f8b080ee0373ed"
GOOGLE_CLIENT_ID = "your-client-id-here"
GOOGLE_CLIENT_SECRET = "your-client-secret-here"
GOOGLE_REDIRECT_URI = "http://localhost:8501/auth/callback"
GOOGLE_AI_STUDIO_KEY =  "AIzaSyBbdHvmKkWBTESy27sBqlISBwMJcK1WDqs"