[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "poll"
folderWatchBlacklist = ['venv', 'env', '.venv', '__pycache__', 'uploads', 'temp', 'user_data', 'users', '.git']

[browser]
gatherUsageStats = false
